name: 'New Chokeco action'
description: This is a composed action example
inputs:
  example_input:
    description: A sample input for the action
    required: true
    default: "default value"
outputs:
  example_output:
    description: The output of the composed action
runs:
  using: "composite"
  steps:
    - name: Run a shell command
      run: echo "This is a shell command, input value: ${{ inputs.example_input }}"

    - name: Set an output
      id: set_output
      run: echo "::set-output name=example_output::${{ inputs.example_input }}"

    - name: Final step
      run: echo "Node.js setup complete!"
